// <auto-generated />
using Constellations.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Constellations.Migrations
{
    [DbContext(typeof(ConstellationDetailsContext))]
    partial class ConstellationDetailsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Constellations.Models.ConstellationDetails", b =>
                {
                    b.Property<int>("ConstellationDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConstellationDetailsID"));

                    b.Property<string>("ConstellationLatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConstellationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConstellationStar")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ConstellationStarDistance")
                        .HasColumnType("int");

                    b.HasKey("ConstellationDetailsID");

                    b.ToTable("ConstellationDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
